@extends('layouts.admin')
@section('content')
<div x-data="distributorManager()" class="space-y-4">
    <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between rounded-3xl border border-white/10 bg-[var(--admin-card)] p-5">
        <form class="flex-1"><input name="q" value="{{ $q }}" placeholder="Rechercher un distributeur..." class="w-full max-w-md rounded-2xl border border-white/10 bg-black/20 px-4 py-3 outline-none"></form>
        <button type="button" @click="openCreate()" class="inline-flex items-center gap-2 rounded-2xl px-4 py-3 text-sm font-extrabold text-white" style="background:linear-gradient(135deg,#1E6FD9,#0f3b8c)"><i class="fa-solid fa-plus"></i><span>Nouveau</span></button>
    </div>
    <div class="rounded-3xl border border-white/10 bg-[var(--admin-card)] p-5 overflow-x-auto">
        <table class="min-w-full text-sm"><thead class="text-white/60"><tr><th class="py-3 pr-4 text-left">Distributeur</th><th class="py-3 pr-4 text-left">Ville</th><th class="py-3 pr-4 text-left">Clients</th><th class="py-3 pr-4 text-left">Commandes</th><th class="py-3 pr-4 text-left">Statut</th><th class="py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($distributors as $d)<tr><td class="py-3 pr-4"><div class="font-bold">{{ $d->nom_frs }}</div><div class="text-xs text-white/60">{{ $d->email }}</div></td><td class="py-3 pr-4">{{ $d->ville ?: '?' }}</td><td class="py-3 pr-4">{{ $d->clients_count }}</td><td class="py-3 pr-4">{{ $d->cmd1_count }}</td><td class="py-3 pr-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ (int)$d->actif === 1 ? 'bg-emerald-500/15 text-emerald-200' : 'bg-red-500/15 text-red-200' }}">{{ (int)$d->actif === 1 ? 'Actif' : 'Inactif' }}</span></td><td class="py-3 text-right"><div class="inline-flex items-center gap-2"><button type="button" @click='openEdit(@json($d))' class="h-9 w-9 rounded-xl border border-white/10 hover:bg-white/10"><i class="fa-solid fa-pen"></i></button><form method="POST" action="{{ url('/admin/distributeurs/'.$d->id.'/toggle-actif') }}" class="inline">@csrf<button class="h-9 w-9 rounded-xl border border-white/10 hover:bg-white/10"><i class="fa-solid {{ (int)$d->actif === 1 ? 'fa-toggle-on text-emerald-300' : 'fa-toggle-off text-red-300' }}"></i></button></form><form method="POST" action="{{ url('/admin/distributeurs/'.$d->id) }}" class="inline" data-confirm-delete data-confirm-title="Supprimer ce distributeur ?" data-confirm-message="Le distributeur {{ $d->nom_frs }} sera retire avec son acces au panel." data-confirm-button="Oui, supprimer le distributeur">@csrf @method('DELETE')<button class="h-9 w-9 rounded-xl border border-white/10 hover:bg-white/10 text-red-300"><i class="fa-solid fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="py-8 text-center text-white/60">Aucun distributeur</td></tr>@endforelse</tbody></table>
    </div>
    <div x-show="open" x-transition class="fixed inset-0 z-50 flex justify-end bg-slate-950/60"><div class="h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-[var(--admin-bg)] p-6"><div class="flex items-center justify-between"><div class="text-xl font-extrabold" x-text="editing ? 'Modifier distributeur' : 'Nouveau distributeur'"></div><button @click="close()" class="h-10 w-10 rounded-xl border border-white/10"><i class="fa-solid fa-xmark"></i></button></div><form class="mt-6 space-y-4" method="POST" :action="action" enctype="multipart/form-data">@csrf<template x-if="editing"><input type="hidden" name="_method" value="PUT"></template><div><label class="mb-2 block text-sm font-semibold">Nom</label><input x-model="form.nom_frs" name="nom_frs" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3" required></div><div><label class="mb-2 block text-sm font-semibold">Email</label><input x-model="form.email" type="email" name="email" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3" required></div><div><label class="mb-2 block text-sm font-semibold">Mot de passe</label><input type="password" name="password" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3" :required="!editing"></div><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="mb-2 block text-sm font-semibold">Telephone</label><input x-model="form.telephone" name="telephone" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Ville</label><input x-model="form.ville" name="ville" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"></div></div><div><label class="mb-2 block text-sm font-semibold">Adresse</label><textarea x-model="form.adresse" name="adresse" rows="3" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"></textarea></div><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="mb-2 block text-sm font-semibold">Latitude</label><input x-model="form.latitude" name="latitude" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Longitude</label><input x-model="form.longitude" name="longitude" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"></div></div><div><label class="mb-2 block text-sm font-semibold">Logo</label><input type="file" name="logo" class="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"></div><label class="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><input type="checkbox" name="actif" value="1" x-model="form.actif"><span class="text-sm font-semibold">Actif</span></label><button class="w-full rounded-2xl px-4 py-3 text-sm font-extrabold text-white" style="background:linear-gradient(135deg,#1E6FD9,#0f3b8c)">Enregistrer</button></form></div></div>
</div>
<script>
function distributorManager(){return{open:false,editing:false,action:'{{ url('/admin/distributeurs') }}',form:{nom_frs:'',email:'',telephone:'',ville:'',adresse:'',latitude:'',longitude:'',actif:true},openCreate(){this.open=true;this.editing=false;this.action='{{ url('/admin/distributeurs') }}';this.form={nom_frs:'',email:'',telephone:'',ville:'',adresse:'',latitude:'',longitude:'',actif:true}},openEdit(d){this.open=true;this.editing=true;this.action='{{ url('/admin/distributeurs') }}/'+d.id;this.form={nom_frs:d.nom_frs ?? '',email:d.email ?? '',telephone:d.telephone ?? '',ville:d.ville ?? '',adresse:d.adresse ?? '',latitude:d.latitude ?? '',longitude:d.longitude ?? '',actif:Number(d.actif)===1}},close(){this.open=false}}}
</script>
@endsection
